version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1  # Espacio añadido después de '-'
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: coverage run -m unittest && coverage xml && coverage report -m
